### ISSUE TITLE
找不到路径

### ISSUE THREAD

**Issue by aimerneige** [kenvix/VSCode-Keil-C51-Environment#1]
![51](https://user-images.githubusercontent.com/51701792/79459193-7ac38280-8025-11ea-806c-77f976832339.PNG)
![51](https://user-images.githubusercontent.com/51701792/79460195-0a1d6580-8027-11ea-8ee1-f4a71fc9589b.PNG)
找不到路径？
Win7的问题吗？Keil可以用。

**Comment by kenvix** [comment]
无法重现问题。请尝试看看.vscode目录下的批处理文件，修改它试试？

**Comment by aimerneige** [comment]
> 无法重现问题。请尝试看看.vscode目录下的批处理文件，修改它试试？

时好时坏，大部分情况是无法使用。
